import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { SidebarProvider } from "~/components/ui/sidebar";
import { Providers } from "~/providers/AuthProvider";
import Player from "~/components/music-player/player";
import LayoutWrapper from "./layout-wrapper";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`}>
			<body>
				<SidebarProvider>
					<Providers>
						<LayoutWrapper>{children}</LayoutWrapper>
					</Providers>
					<Player />
				</SidebarProvider>
			</body>
		</html>
	);
}
